name: Build APK

on:
  push:
    branches:
      - "**"
  pull_request:
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: "21"
          cache: gradle

      - name: Build debug APK
        run: ./gradlew assembleDebug --stacktrace

      - name: Build release APK
        run: ./gradlew assembleRelease --stacktrace

      - name: Prepare artifact names
        run: |
          VERSION_NAME="$(jq -r '.elements[0].versionName' app/build/outputs/apk/release/output-metadata.json)"
          echo "VERSION_NAME=$VERSION_NAME" >> "$GITHUB_ENV"
          mv app/build/outputs/apk/release/*.apk "app/build/outputs/apk/release/Harmony_v$VERSION_NAME-release.apk"
          mv app/build/outputs/apk/debug/*.apk "app/build/outputs/apk/debug/Harmony_v$VERSION_NAME-debug.apk"

      - name: Upload debug APK
        uses: actions/upload-artifact@v6
        with:
          name: harmony-debug-apk
          path: app/build/outputs/apk/debug/*.apk

      - name: Upload release APK
        uses: actions/upload-artifact@v6
        with:
          name: harmony-release-apk
          path: app/build/outputs/apk/release/*.apk
